### ISSUE TITLE
HITs getting "hung up" because of an expired approval?

### ISSUE THREAD

**Issue by vitorio** [ryantate/typingpool#6]
I skipped an approval, went to bed, and six hours later, I assume it auto-paid.

After that timeout occurred, `tp-review` did not present it to me again, but also did not present to me any new approvals, either:

```
Figuring out what needs to be assigned
41 assignments total
10 assignments completed
31 assignments outstanding
Nothing to assign
```

I've continued to receive no assignments, and there has been no change in `tp-review` reporting, but looking at Amazon's HIT review interface, every assignment now has a "Reviewed Assignment" which I did not manually approve:

![screen shot 2013-12-03 at 12 12 09 pm](https://f.cloud.github.com/assets/336712/1666407/83436cb8-5c46-11e3-9d22-4ed0d0f1f8b2.png)

`tp-finish` did not retrieve any of the auto-approved entries, and it does not appear that there is a way to download those results, which are now no longer present on the MTurk site (also, since they were individual HITs and not a batch, it did not appear as if I could have downloaded the results other than one at a time).

Is this enough information or would you like a more detailed test case?

**Comment by ryantate** [comment]
tp-review now collects auto-approved HITs (and anything else tp-collect would collect - it even passes the exact same tests :-)

will close this issue with the new commit shortly.
