### ISSUE TITLE
Update needed for mechanical turk new pricing structure

### ISSUE THREAD

**Issue by randywreed** [ryantate/typingpool#9]
Amazon has implemented a new fee structure. Amazon says "20% fee on the reward and bonus amount (if any) you pay Workers. HITs with 10 or more assignments will be charged an additional 20% fee on the reward you pay Workers. The minimum fee is $0.01 per assignment or bonus payment." Currently it looks like tp-assign uses a 10% fee. Code should be updated.

btw. Just used this last night for a transcription and it worked great. Thank you for it.

**Comment by ryantate** [comment]
Thanks for the heads up Randy and glad it was of some help. This issue should be fixed in the new version I just pushed (here and at rubygems) v0.8.11. Sorry to miss this for so long.
